project:
  type: website
  output-dir: _site
plugins:
    - last_modified
website:
  title: "WFTDM Documentation"
  favicon: _pictures/favicon.ico
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"
    left: |
      [![](https://wfrc.org/wp-content/uploads/2021/11/logo.jpg){fig-alt='WFRC' width=150px}](https://wfrc.org) 
      [![](https://mountainland.org/static/media/logo/svg/MAG_Logo_Horz_NoTag.svg){fig-alt='MAG' width=65px}](https://mountainland.org/)
  navbar:
    background: info
    logo: _pictures/wf-logo-new-white-t.png
    logo-href: https://wfrc.org
    tools:
      - icon: github
        href: https://github.com/WFRCAnalytics/TDM-Documentation/tree/gh-pages
      - icon: envelope
        href: mailto:sswim@wfrc.org
    title: false
    collapse-below: lg
    left:

      - text: "Overview"
        href: index.qmd

      - text: "Version 9 Series"
        menu:
        - text: "Version 9.0.0" 
          href: v9x/v900/index.qmd
          id: v900-preface

      - text: "Past Versions"
        menu:
        - text: "Version 8.3.2 - Draft Release"
          href: v8x/v832/index.qmd 
          id: v832-preface
        - text: "Version 8.3.1 - Draft Release"
          href: v8x/v831/index.qmd
          id: v831-preface
        - text: "Version 8.3.0 - Draft Release"
          href: v8x/v830/index.qmd
          id: v830-preface
          
  sidebar:
    - id: v900-preface
      style: "docked"
      collapse-level: 1
      border: true
      background: white
      contents:
        - section: "<span style=\"color: #3E6682;font-size: 25px;\">**Version 9.0.0**</span>"
          contents:
            - "---"
            - v9x/v900/index.qmd
            #- text: "**Downloads**"
            #  href: v9x/v900/downloads.qmd
            - "---"
            - section: "<span style=\"color: #3E6682;\">**Whats New Document**</span>"
              contents:
                - text: "1 Overview"
                  href: v9x/v900/whats-new/1-overview.qmd  
                - text: "2 Traffic Analysis Zone Updates"
                  href: v9x/v900/whats-new/2-taz.qmd
                - text: "3 Socioeconomic Data Updates"
                  href: v9x/v900/whats-new/3-sedata.qmd
                - text: "4 Highway & Transit Networks Updates"
                  href: v9x/v900/whats-new/4-networks.qmd
                - text: "5 Model 2019 Base-Year Updates"
                  href: v9x/v900/whats-new/5-baseyear.qmd
                - text: "6 Model Enhancements"
                  href: v9x/v900/whats-new/6-modelenhancements.qmd
                - text: "7 Compare Model Results"
                  href: v9x/v900/whats-new/7-modelresults.qmd
            - "---"
            - section: "<span style=\"color: #3E6682;\">**Model Validation Report**</span>"
              contents:
            #    - v9x/v900/validation/1-hhdisag-autoown.qmd
                - text: "1 Trip Generation"
                  href: v9x/v900/validation/1-tripgen.qmd
                - text: "2 Distribution"
                  href: v9x/v900/validation/2-distribute.qmd
                - text: "3 Mode Choice"
                  href: v9x/v900/validation/3-modechoice.qmd
                - text: "4 Highway Assignment"
                  href: v9x/v900/validation/4-assignhwy.qmd
            #    - v9x/v900/validation/A-sensitivity.qmd
            - "---"
            #- section: "<span style=\"color: #3E6682;\">**Model Process**</span>"
            #  contents:
            #    - v9x/v900/model-process/1-hhdisag-autoown.qmd
            #    - v9x/v900/model-process/2-tripgen.qmd
            #    - v9x/v900/model-process/3-distribute.qmd
            #    - v9x/v900/model-process/4-modechoice.qmd
            #    - v9x/v900/model-process/5-assignhwy.qmd
            #    - v9x/v900/model-process/A-sensitivity.qmd
            #- "---"
    - id: v832-preface
      style: "docked"
      collapse-level: 4
      border: true
      background: white
      contents:
        - section: "<span style=\"color: #3E6682;font-size: 25px;\">**Version 8.3.2 - <br>Draft Release**</span>"
          contents:
          - "---"
          - text: "Preface"
            href: v8x/v832/index.qmd
          - text: "Downloads"
            href: v8x/v832/downloads.qmd
        - "---"
        - section: "<span style=\"color: #3E6682;\">**Whats New Document**</span>"
          contents:
          - text: "2022-02-04 Update"
            href: v8x/v832/whats-new/1-20220204-update.qmd
          - text: "General Parameters"
            href: v8x/v832/whats-new/1-genparams.qmd
          - text: "Input Data"
            href: v8x/v832/whats-new/2-inputdata.qmd
          - text: "Input Processing"
            href: v8x/v832/whats-new/3-inputprocessing.qmd
          - text: "Household Disaggregation and Auto Ownership"
            href: v8x/v832/whats-new/4-hhdisag.qmd
          - text: "Trip Generation"
            href: v8x/v832/whats-new/5-tripgen.qmd
          - text: "Distribution"
            href: v8x/v832/whats-new/6-distribution.qmd
          - text: "Mode Choice"
            href: v8x/v832/whats-new/7-mc.qmd
          - text: "Highway Assignment"
            href: v8x/v832/whats-new/8-assign.qmd
          - text: "Post Processing"
            href: v8x/v832/whats-new/9-pp.qmd
          - text: "Model Results - Comparison with v8.3.1"
            href: v8x/v832/whats-new/10-modelresults.qmd
          - "---"
    - id: v831-preface
      style: "docked"
      collapse-level: 4
      border: true
      background: white
      contents:
        - section: "<span style=\"color: #3E6682;font-size: 25px;\">**Version 8.3.1 - <br>Draft Release**</span>"
          contents:
          - "---"
          - text: "Preface"
            href: v8x/v831/index.qmd
          - text: "Downloads"
            href: v8x/v831/downloads.qmd
        - "---"
        - section: "<span style=\"color: #3E6682;\">**Whats New Document**</span>"
          contents:
            - text: '2020-08-17 Update'
              href: v8x/v831/whats-new/1-20200817-update.qmd
            - text: 'Input Data'
              href: v8x/v831/whats-new/1-inputdata.qmd
            - text: 'Update for Cube 6.4.5'
              href: v8x/v831/whats-new/2-cube-update.qmd
            - text: 'Segment Summary'
              href: v8x/v831/whats-new/3-segsum.qmd
            - text: 'Assignment Output Folder'
              href: v8x/v831/whats-new/4-assign.qmd
            - text: 'Access to Opportunity'
              href: v8x/v831/whats-new/5-ato.qmd
            - text: 'Miscellaneous Changes'
              href: v8x/v831/whats-new/6-misc.qmd
            - "---"
    - id: v830-preface
      style: "docked"
      collapse-level: 4
      border: true
      background: white
      contents:
        - section: "<span style=\"color: #3E6682;font-size: 25px;\">**Version 8.3.0 - <br>Draft Release**</span>"
          contents:
          - "---"
          - text: "Preface"
            href: v8x/v830/index.qmd
          - text: "Downloads"
            href: v8x/v830/downloads.qmd
          - "---"

format:
  html:
    grid:
      sidebar-width: 380px
      gutter-width: 40px
      margin-width: 350px
    toc: true
    toc-depth: 2
    toc-location: right
    toc-title: "**Section Contents**<br>__________________"

    mainfont: "Ebrima"
    fontsize: 11.5pt
    linkcolor: "#789d4b"

    theme:
      - cerulean
      - custom.scss
    code-fold: true
    number-depth: 6





